sudo:
  - required

services:
  - docker

language: python

script:
  - pwd
  - ls -la
  - python -m pytest -v

after_success:

  - ls .travis/docker_dockerhub.sh
  - cat .travis/docker_dockerhub.sh
  - which sh
  - ls -la .travis/deploy_dockerhub.sh
  - /bin/sh .travis/deploy_dockerhub.sh
