sudo:
  - required

services:
  - docker

language: python

script:
  - pwd
#  - python -m pytest -v

#after_success:

#  - ls ~/.travis/deploy_dockerhub.sh
#  - sudo /bin/sh .travis/deploy_dockerhub.sh
